### ISSUE TITLE
Issue when sending ResultsTable to OMERO

### ISSUE THREAD

**Issue by Rdornier** [GReD-Clermont/omero_batch-plugin#13]
Hello, 

I have an issue when I try to save ResultsTable on OMERO, whatever if I use a macro or a groovy script
I [ attached ](https://github.com/GReD-Clermont/omero_batch-plugin/files/10207003/Omero_Fiji.zip)the macro file and the groovy script so that you can try. I use images coming from this [zenodo repo](https://zenodo.org/record/4248921#.Y5b9Cn3MK4S).

Images are uploaded on OMERO and I want to save back on OMERO (if I save locally, everything goes well). If I select only `ROIs`, the batch process doesn't crash and ROIs are uploaded on OMERO, attached to the correct image.

But when I tick `Results Table(s)` box, and then `start`, I have a popup at the end of the processing of the first image and then, whatever the answer, it throws the following error.

![BatchPluginBug](https://user-images.githubusercontent.com/64911638/207022694-43998814-c977-414c-b205-cb039207318c.png)

Popup message 

![BatchPluginBugPopup](https://user-images.githubusercontent.com/64911638/207022714-5b4e2c33-240d-4051-894f-4a17bc736d55.png)

```
Exception in thread "Thread-768" java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@6354bff3 rejected from java.util.concurrent.ThreadPoolExecutor@554890ae[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at omero.gateway.Gateway.submit(Gateway.java:278)
	at omero.gateway.facility.DataManagerFacility.attachFile(DataManagerFacility.java:720)
	at fr.igred.omero.repository.GenericRepositoryObjectWrapper.addFile(GenericRepositoryObjectWrapper.java:547)
	at fr.igred.ij.macro.OMEROBatchRunner.uploadFile(OMEROBatchRunner.java:870)
	at fr.igred.ij.macro.OMEROBatchRunner.saveResults(OMEROBatchRunner.java:835)
	at fr.igred.ij.macro.OMEROBatchRunner.save(OMEROBatchRunner.java:699)
	at fr.igred.ij.macro.OMEROBatchRunner.runMacro(OMEROBatchRunner.java:552)
	at fr.igred.ij.macro.OMEROBatchRunner.run(OMEROBatchRunner.java:427)
```

Do you have an idea on what can be the issue ?
Thanks, 

Best,
Rémy.

**Comment by ppouchin** [comment]
Hello @Rdornier,

I think we saw something like that at one point, but it was not really reproducible.
Although I'm not sure it's the same, in our case it disappeared by restarting Fiji or the server.

If it's persistent, it might be related to the script that runs. Do you have the same problem if you run scripts to save tables from [this repo](https://github.com/ppouchin/i2k-2022-workshop)?

**Comment by Rdornier** [comment]
Hello @ppouchin , 

Thanks for your suggestions. 
Indeed, it completly disappear today, as I have restarted my Fiji !

I have also try [this script](https://github.com/ppouchin/i2k-2022-workshop/blob/main/1-segmentation/2D-segmentation-rois.ijm) for your repo and it also works fine.

> by restarting Fiji or the server.

Good to know that it can also be due to the server.

All the best,
Rémy.
